# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jack Hallahan – UX Designer
email: hello@jackhallahan.com
description: > # this means to ignore newlines until "baseurl:"
  The personal portfolio of Jack Hallahan, UX/UI and product designer.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://jackhallahan.com" # the base hostname & protocol for your site
twitter_url: https://twitter.com/jahallahan
dribbble_url:  https://dribbble.com/jahallahan
permalink: none

# Build settings
markdown: kramdown
exclude: ['node_modules']
